### ISSUE TITLE
Just wanted to thank lrhodes404 for the tracker support!

### ISSUE THREAD

**Issue by AbsoLootAaron** [Colossus-Gaming/retroachievements-layout-manager#20]
Thanks for updating the best cheevo tracker available, while we're still waiting for the RA web API to be fully enabled again! :) Appreciate you bunches, and for your dedicated work! :D
Keep it up buddy. *Salute*
P.S. Hopefully the changes/updates to the RA web won't be too much of a problem for you?

**Comment by Ekiinoxx** [comment]
Yep a big thank you lrhodes404, I've been using this tracker for a long time and was really bummed to see it discontinued. The RA API is back and so is the tracker :) . Just a few adjustments to make. When the tracker was updated, there was a problem with the user info. RetroS3xual's info appeared instead of ours. Also, with the return of the tracker two days ago, cheevos unlocking is now done manually instead of automatically, which is a bit annoying. 

Thanks again for the update lrhodes404, really appreciated :) 

![2023-11-21_105225](https://github.com/Colossus-Gaming/retroachievements-layout-manager/assets/151623927/d76dad5b-269d-486b-9ca6-5f1cab9f4065)   I'm attaching a screen of the user info that appears on the tracker (to show that it's not ours)

**Comment by AbsoLootAaron** [comment]
The RA tracker still doesn't work for me. When I press start, it'll just say "API_GetGameInfoAndUserProgress is down."
So the RA web API isn't fully enabled just yet. We'll probably see an update about the API later this month, or next month at the latest. They've been making good progress on the web updates though! :)
Earlier this month, Luchaos posted some community news on their RA discord server about the new servers being implemented. Once the new servers have settled in they'll re-evaluate enabling the web API again. So we gotta wait just a little bit longer.
