### ISSUE TITLE
All Achievements and Game Info reverting back to previous game

### ISSUE THREAD

**Issue by x10power** [Colossus-Gaming/retroachievements-layout-manager#23]
Hello,

So I have the latest version that was released today and I am  encountering an issue I can't seem to figure out why it is happening to me.

I type in the game I want to play tonight into the Game ID space and hit search it appears as normal. The moment I hit the start button it switches back to the previous game I already mastered. 

I did some digging around and seeing the the data file in RA Layout Manager > stream-labels > game info will change when I type in the game id but will revert the moment I hit start. 

This is the game it keeps reverting back to the moment I hit the 

This is before I hit the Start button (Donkey Kong #692)
![Screenshot 2023-12-08 192610](https://github.com/Colossus-Gaming/retroachievements-layout-manager/assets/21017114/54879fc1-c556-4349-b2cd-529baeef5398)

This what happens after I hit the start button (Clockwork Knight is #14516)
![Screenshot 2023-12-08 192706](https://github.com/Colossus-Gaming/retroachievements-layout-manager/assets/21017114/a1c08845-aa02-42a3-bf7d-22a59eb85e56)

Thank you for everything you created!

**Comment by lrhodes404** [comment]
Pressing "Start" will instruct the app to pull info for the most recently played game on Retro Achievements and will update every 30 seconds to pull the latest progression on that game until you play another one on RA. Using the "Search" button will manually search for whatever game id you put in and was only intended to give some functionality while the User Progress endpoints were disabled for the past few months. What is your most recently played game on RA and if it's not what the tracker is pulling, I will take a look. Keep in mind it may take a minute for it show up on the tracker due to the fact it only polls every 30s and the public RA Web API takes a minute before it returns the most up-to-date data.

**Comment by x10power** [comment]
My most recent game was Clockwork Knight which was play a few days ago. I wanted to switch to Donkey Kong and have it do the auto tracking for me. Now that I am typing this message it working as intended! Might want to give a warning of some sort or a pop up mentioning this in the program if possible. 

Thank You Again!

**Comment by x10power** [comment]
I just did a test just to see what is going on exactly so I could see what is going on exactly. Since I was on Donkey Kong 692 I thought I would try and switch to Sonic the Hedgehog (Genesis) which is number 1. So I click stop, switch the game from DK to Sonic , then press Start. I continue to wait multiple minutes for it not to change at all. If you want video of what I am trying to do I could make a recording after work tomorrow!

**Comment by x10power** [comment]
Okay after doing 1 more test I know what made it change games now! It's not the search function inside the tracker but when you actually load the game in (my case) Retroarch. I want to thank you for your support and admit user error on this issue!

**Comment by lrhodes404** [comment]
Glad it's still working as intended. Happy hunting!
