### ISSUE TITLE
unresizeable windows. Text doesn't fit

### ISSUE THREAD

**Issue by chocolatiel** [Colossus-Gaming/retroachievements-layout-manager#8]
After one of those **forced** updates (_would love to be asked if I want to or not_), layout got screwed, text won't fit anymore and windows can not be resized. I wish I could keep using your tool with my layout :) Thank you for amazing tool.

[it looks like this](https://ibb.co/SQN0Lzd)

**Comment by lrhodes404** [comment]
Hi there, I will certainly look into not forcing updates but I have a question about the text. Another user reported this as an issue and it turns out they had changed their DPI settings. Have you changed any settings on your computer recently that affects font size and readability?

**Comment by chocolatiel** [comment]
Thank you for replying. I haven't changed any config in my pc lately, and I had to look for what is DPI, and no, I always try to avoid fixing things that aren't broken. So I'm not sure if I shoud go regedit to try to make font fit in windows of tracker. atm, I'll just keep checking from time to time if font will ever fit for me again or if at some point tracker windows can be resized again. Thank you so much for all you do! :)

**Comment by LordBBH** [comment]
I've been having the same issue, and it is a DPI thing. My eyesight's a little bad and my monitor's a little small so my DPI's always been turned up to 125%. This wasn't an issue when I first installed the program, but roughly 4 weeks ago or so the new update broke the window sizing on things like Focus and Achievement List, and there's no way to resize them. Would love to rollback to an earlier release where the font size fit in the window normally, but since auto-update is always on those old versions can never be used again.

**Comment by lrhodes404** [comment]
Sorry to hear that this happened. I'm currently working on a new version not built on WinForms and will hopefully alleviate any of these issues. I'll also keep in mind not automating the updates and just prompting once if a user once to ignore it. I will hopefully have it out within a few weeks and will be less bloated than this current version. Again, I apologize I don't have more to offer for now until the next iteration is ready.

**Comment by Dcat682** [comment]
I'm having this issue as well as I run everything at 125% on my computer due to poor eyesight.  I don't know what's feasible with programming, but if you're able to give us a setting to adjust the resolution scaling by either grabbing the sides and stretching or a text box we can type a number into that would be amazing.  

Changing a setting to make everything unreadable on my computer to make one program to run isn't a good long term solution.

**Comment by lrhodes404** [comment]
I have built a version that rolls back the library that renders the text to see if that can alleviate the problem of font being oversized for whatever reason as well as enabling the resizing of windows. To install it properly you MUST uninstall the current version or delete the CefSharp DLL files in the app's directory before running the installer found here: https://github.com/Colossus-Gaming/retroachievements-layout-manager/releases/download/v1.22.12/RALayoutManagerInstaller.msi
I don't know if this will help the issue but it's worth a shot if it will resolve this issue for you guys.

**Comment by lrhodes404** [comment]
Also, to avoid auto-updating, simple decline the install when it pops up for now. Once I find a more permanent solution and implement a better updating experience, I will push that out.

**Comment by LordBBH** [comment]
Uninstalled and reinstalled this version, it works! The first time I loaded the Focus window the text was partially cut off and wasn't being redrawn when resized, but closing the Focus window and then reopening it made it display correctly the second time. Weird. The Achievement List looks good again too. Thank you for looking into this!

**Comment by Dcat682** [comment]
Great fix!  That was really fast and worked right away!
